### ISSUE TITLE
Proposal: Feedback

### ISSUE THREAD

**Issue by s-pangburn** [eaconway/Airbnb-Clone#1]
Hey E.J! Hope you're doing well 🙂 Here's my feedback for your proposal:

Nothing!

Well, that was a lie, one thing:

- [x] Frontend routes, wrap your routes in `backticks` instead of 'single quotes'

But that's really it! This is a really comprehensive proposal, great job! 😄 You should be good to go for tomorrow as soon as you fix that one thing.

**Comment by eaconway** [comment]
Done!

**Comment by s-pangburn** [comment]
:+1:
